services:

  mongo:
    image: mongo
    restart: always
    env_file: 
      - ./.env
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: 
      - ./.env

  quivia-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: quivia-backend
    restart: always
    ports:
      - 8082:3000
    env_file: 
      - ./.env
    depends_on:
      - mongo

volumes:
  mongodb_data:
    driver: local